# Generated by Django 5.2.17 on 2026-08-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
