# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(
                default='',
                verbose_name='Краткое описание',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(
                null=True,
                verbose_name='Краткое описание',
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ky',
            field=models.TextField(
                null=True,
                verbose_name='Краткое описание',
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(
                null=True,
                verbose_name='Краткое описание',
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(
                default='',
                unique=True,
                verbose_name='Ссылка',
            ),
            preserve_default=False,
        ),
    ]
    
