# Generated by Django 6.1 on 2026-08-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_ky',
            new_name='name_ky',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_ru',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
