# Generated by Django 6.1 on 2026-08-30 09:07

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_en',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_ky',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_ru',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), common.validators.validate_image_size, common.validators.validate_image_dimensions], verbose_name='Картинка'),
        ),
    ]
