# Generated by Django 6.1 on 2026-09-15 16:55

import django.core.validators
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_description_alter_post_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Обработано'), ('failed', 'Ошибка обработки'), ('skipped', 'Сжатие не требуется')], default='skipped', max_length=20, verbose_name='Статус обработки изображения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), common.validators.validate_image_size], verbose_name='Картинка'),
        ),
    ]
