# Generated by Django 6.1 on 2026-09-23 11:25

import django.core.validators
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_image_processing_status_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), common.validators.validate_image_size, common.validators.validate_image_integrity], verbose_name='Картинка'),
        ),
    ]
