# Generated by Django 5.2.17 on 2026-08-11 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_email_alter_baseuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(help_text='Пример: +996555123456', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+996XXXXXXXXX' (всего 12 цифр).", regex='^\\+996\\d{9}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
