# Generated by Django 6.1 on 2026-09-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_phone_alter_baseuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
    ]
