# Generated by Django 5.2.17 on 2026-08-11 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+996XXXXXXXXX' (всего 12 цифр).", regex='^\\+996\\d{9}$')], verbose_name='Номер телефона'),
        ),
    ]
