# Generated by Django 5.2.17 on 2026-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_baseuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Образование или ученая степень'),
        ),
    ]
