# Generated by Django 5.2.17 on 2026-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctorprofile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Образование или место учебы'),
        ),
    ]
