# Generated by Django 6.1 on 2026-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('topic', models.CharField(choices=[('medical_help', 'Медицинская помощь'), ('cooperation', 'Сотрудничество'), ('partnership', 'Партнерство')], max_length=20, verbose_name='Тема обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
