# Generated by Django 6.1 on 2026-09-29 12:50

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('topic', models.CharField(choices=[('medical_help', 'Медицинская помощь'), ('cooperation', 'Сотрудничество'), ('partnership', 'Партнерство')], max_length=20, verbose_name='Тема обращения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Рассмотрена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
            },
        ),
        migrations.CreateModel(
            name='EditableTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Используется разработчиком в шаблонах', max_length=100, unique=True, verbose_name='Уникальный идентификатор (Slug)')),
                ('content', models.TextField(verbose_name='Содержимое текста')),
                ('content_ru', models.TextField(null=True, verbose_name='Содержимое текста')),
                ('content_ky', models.TextField(null=True, verbose_name='Содержимое текста')),
                ('content_en', models.TextField(null=True, verbose_name='Содержимое текста')),
            ],
            options={
                'verbose_name': 'Редактируемый текстовый блок',
                'verbose_name_plural': 'Редактируемые текстовые блоки',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО / название организации')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО / название организации')),
                ('full_name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО / название организации')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО / название организации')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Краткая информация')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Краткая информация')),
                ('bio_ky', models.TextField(blank=True, null=True, verbose_name='Краткая информация')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Краткая информация')),
                ('category', models.CharField(choices=[('founder', 'Учредители'), ('ambassador', 'Посол Доброй воли'), ('board', 'Управляющий совет'), ('team', 'Команда Ассоциации')], max_length=20, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), common.validators.validate_image_size], verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда и руководство',
                'ordering': ['order', 'id'],
            },
        ),
    ]
