# Generated by Django 5.2.17 on 2026-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Рассмотрена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
