<<<<<<< HEAD
# Generated by Django 6.1 on 2026-09-05 16:07
=======
# Generated by Django 5.2.17 on 2026-09-05 15:59
>>>>>>> origin/dev

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_consultationrequest_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'verbose_name': 'Заявка на консультацию', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
    ]
