# Generated by Django 5.2.17 on 2026-09-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_consultationrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Используется разработчиком в шаблонах', max_length=100, unique=True, verbose_name='Уникальный идентификатор (Slug)')),
                ('content', models.TextField(verbose_name='Содержимое текста')),
                ('content_ru', models.TextField(null=True, verbose_name='Содержимое текста')),
                ('content_ky', models.TextField(null=True, verbose_name='Содержимое текста')),
                ('content_en', models.TextField(null=True, verbose_name='Содержимое текста')),
            ],
            options={
                'verbose_name': 'Редактируемый текстовый блок',
                'verbose_name_plural': 'Редактируемые текстовые блоки',
                'ordering': ['slug'],
            },
        ),
    ]
