# Generated by Django 6.1 on 2026-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='В формате +996312214015', max_length=20, verbose_name='Телефон для tel:-ссылки')),
                ('phone_display', models.CharField(max_length=30, verbose_name='Телефон (отображаемый текст)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='Ссылка WhatsApp')),
                ('whatsapp_display', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp (отображаемый текст)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Ссылка Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Ссылка Instagram')),
                ('twogis_url', models.URLField(blank=True, verbose_name='Ссылка на 2ГИС')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакты сайта',
                'verbose_name_plural': 'Контакты сайта',
            },
        ),
    ]
