# Generated by Django 5.2.17 on 2026-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_registration_enabled', models.BooleanField(default=True, verbose_name='Регистрация пациентов включена')),
                ('doctor_registration_enabled', models.BooleanField(default=True, verbose_name='Регистрация врачей включена')),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
            },
        ),
    ]
