# Generated by Django 5.2.17 on 2026-09-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_systemsettings'),
        ('main', '0007_seed_site_contacts'),
    ]

    operations = [
    ]
