# Generated by Django 5.2.17 on 2026-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_editabletextblock_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaleditabletextblock',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Содержимое текста'),
        ),
        migrations.AddField(
            model_name='historicaleditabletextblock',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Содержимое текста'),
        ),
        migrations.AddField(
            model_name='historicaleditabletextblock',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержимое текста'),
        ),
    ]
