# Generated by Django 5.2.17 on 2026-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_historicaleditabletextblock_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editabletextblock',
            name='slug',
            field=models.SlugField(help_text='Используется разработчиком в шаблонах', max_length=100, verbose_name='Уникальный идентификатор (Slug)'),
        ),
        migrations.AddConstraint(
            model_name='editabletextblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='unique_slug_for_active_blocks'),
        ),
    ]
