# Generated by Django 6.1 on 2026-08-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_baseuser_phone_alter_baseuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название симптома')),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптомы',
            },
        ),
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('medications', models.TextField(blank=True, verbose_name='Принимаемые препараты')),
                ('contraindications', models.TextField(blank=True, verbose_name='Противопоказания')),
                ('previous_treatment', models.TextField(blank=True, verbose_name='Ранее проведенное лечение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to='accounts.doctorprofile', verbose_name='Лечащий врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_cards', to='accounts.patientprofile', verbose_name='Пациент')),
                ('symptoms', models.ManyToManyField(blank=True, to='patients.symptom', verbose_name='Симптомы')),
            ],
            options={
                'verbose_name': 'Карточка пациента',
                'verbose_name_plural': 'Карточки пациентов',
            },
        ),
    ]
