# Generated by Django 6.1 on 2026-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientcard_id_alter_symptom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название симптома'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название симптома'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название симптома'),
        ),
    ]
