# Generated by Django 5.2.17 on 2026-08-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patientcard_id_alter_symptom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('audience', models.CharField(choices=[('specialist', 'Руководство для специалистов'), ('caregiver', 'Советы ухаживающим')], max_length=20, verbose_name='Целевая аудитория')),
                ('subcategory', models.CharField(choices=[('symptom_control', 'Контроль симптомов'), ('end_of_life_care', 'Уход в конце жизни'), ('npa', 'НПА (Нормативно-правовые акты)'), ('care_feeding', 'Уход и кормление'), ('psychologist_tips', 'Советы психолога'), ('meds_rights', 'Лекарства и права пациента'), ('social_support', 'Соцподдержка')], max_length=30, verbose_name='Подкатегория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='resources', to='patients.symptom', verbose_name='Симптомы')),
            ],
            options={
                'verbose_name': 'Справочный материал',
                'verbose_name_plural': 'Справочные материалы',
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resources/files/', verbose_name='Файл')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Файл ресурса',
                'verbose_name_plural': 'Файлы ресурса',
            },
        ),
        migrations.CreateModel(
            name='ResourceVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на YouTube')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='resources.resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Видео-ссылка',
                'verbose_name_plural': 'Видео-ссылки',
            },
        ),
    ]
