# Generated by Django 6.1 on 2026-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
