# Generated by Django 6.1 on 2026-09-06 12:20

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')

    for resource in Resource.objects.all():
        base_slug = slugify(resource.title_ru or resource.title, allow_unicode=True)
        slug = base_slug
        counter = 1
        while Resource.objects.filter(slug=slug).exclude(pk=resource.pk).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        resource.slug = slug
        resource.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    Resource.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]