# Generated by Django 6.1 on 2026-09-06 13:09

from django.db import migrations
from django.utils.text import slugify
from transliterate import translit


def retranslit_slugs(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    for resource in Resource.objects.all():
        latin_title = translit(resource.title_ru, 'ru', reversed=True)
        base_slug = slugify(latin_title)
        slug = base_slug
        counter = 1
        while Resource.objects.filter(slug=slug).exclude(pk=resource.pk).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        resource.slug = slug
        resource.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0005_alter_resource_slug'),
    ]
    operations = [
        migrations.RunPython(retranslit_slugs, noop),
    ]