# Generated by Django 6.1 on 2026-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_retranslit_resource_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
