# Generated by Django 6.1 on 2026-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Обработано'), ('failed', 'Ошибка обработки'), ('skipped', 'Сжатие не требуется')], default='skipped', max_length=20, verbose_name='Статус обработки файла'),
        ),
    ]
