# Generated by Django 6.1 on 2026-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='audience',
            field=models.CharField(choices=[('specialist', 'Руководство для специалистов'), ('caregiver', 'Советы ухаживающим'), ('pediatric', 'Паллиативная педиатрия')], max_length=20, verbose_name='Целевая аудитория'),
        ),
    ]
