# Generated by Django 6.1 on 2026-09-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_resource_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Термин')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Термин')),
                ('name_ky', models.CharField(max_length=255, null=True, unique=True, verbose_name='Термин')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('definition_ru', models.TextField(null=True, verbose_name='Определение')),
                ('definition_ky', models.TextField(null=True, verbose_name='Определение')),
                ('definition_en', models.TextField(null=True, verbose_name='Определение')),
            ],
            options={
                'verbose_name': 'Медицинский термин',
                'verbose_name_plural': 'Медицинские термины',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.term', verbose_name='Термины'),
        ),
    ]
