# Generated by Django 6.1 on 2026-10-01 10:22
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_merge'),
    ]
    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subcategory',
            field=models.CharField(choices=[('symptom_control', 'Контроль симптомов'), ('end_of_life_care', 'Уход в конце жизни'), ('npa', 'НПА (Нормативно-правовые акты)'), ('care_feeding', 'Уход и кормление'), ('psychologist_tips', 'Советы психолога'), ('pain_management', 'Управление болью'), ('meds_rights', 'Лекарства и права пациента'), ('social_support', 'Соцподдержка')], max_length=30, verbose_name='Подкатегория'),
        ),
    ]