# Generated by Django 6.1 on 2026-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/converted/', verbose_name='PDF-версия (из Word)'),
        ),
    ]
