# Generated by Django 6.1 on 2026-10-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_resource_subcategory'),
        ('resources', '0010_resourcefile_converted_pdf'),
    ]

    operations = [
    ]
